# Configuration file to build a conda environment where
# all relevant packages to run the GRBModelling class are installed
# using the right version
#
# Author: Carlo Romoli (MPIK)
#
name: grbmodel
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.6
  - h5py=2.9.0
  - astropy=3.2.1
  - ipython=7.6.1
  - emcee=2.2.1
  - naima=0.8.3
  - numpy=1.16.4
  - scipy=1.3.1
  - matplotlib=3.2.1

